openipam/django-openipam

openipam/api/views/base.py
=> Fix API traceback when limit is not specified

openipam/api/urls.py, openipam/api/views/report.py, openipam/report/static/report/css/svg.css, openipam/report/static/report/css/uplinks.css, openipam/report/static/report/js/weathermap.js, openipam/report/templates/report/base.html, openipam/report/templates/report/building_map.html, openipam/report/urls.py, openipam/report/views.py
* Added padding to body in svg.css to shift window content to be below navbar for pages with svgs
=> Adds building map page; fixes weathermap css

openipam/api/serializers/network.py, openipam/api/urls.py, openipam/api/views/network.py, openipam/network/models.py
Adds API access for:
* DhcpGroup
* DhcpOption
* DhcpOptionToDhcpGroup
* SharedNetwork
* NetworkRange
* NetworkToVlan
* Pool
* DefaultPool
* Vlan
=> Expands Network API

openipam/report/static/report/js/weathermap.js, openipam/report/templates/report/building_map.html
* Sorts buildings alphabetically
* Adds building numbers
* Adds remote sites
* Adds visual indication that a connection is down
=> Adds building numbers/remote site data

openipam/api/views/hosts.py, openipam/api/views/network.py, openipam/core/management/commands/add_view_permissions.py, openipam/core/templatetags/openipam.py, openipam/core/utils/sql_log.py, openipam/dns/views.py, openipam/hosts/views.py, openipam/user/utils/user_utils.py
Parentheses after print and no except Exception, e
=> Fix enough python2-isms for python3.7 AST to parse

openipam/hosts/models.py
Also ignore the Host field (mac column in db)
=> Missed the host/mac column

openipam/api/views/report.py, openipam/dns/forms.py, openipam/dns/static/dns/js/dnsrecord_list.js, openipam/dns/views.py, openipam/hosts/views.py
=> -Disable DNS Type edit per Eldon request.

openipam/network/forms.py, openipam/network/models.py
=> bug fix for #69

openipam/api/serializers/network.py, openipam/api/views/network.py, openipam/network/admin.py, openipam/network/models.py
=> additional (potentially breaking) api changes to allow for crud operations

openipam/report/static/report/css/uplinks.css, openipam/report/static/report/js/weathermap.js, openipam/report/templates/report/building_map.html
Make it so there isn't an unnecessary svg on the building map.
=> rework building map structure to make more sense

.gitignore, node_modules/.gitignore, openipam/api/views/report.py, openipam/core/admin.py, openipam/core/items.py, openipam/core/menu.py, openipam/core/static/core/css/style.css, openipam/core/templates/admin/change_form.html, openipam/core/templates/admin/object_history.html, openipam/dns/admin.py, openipam/dns/models.py, openipam/hosts/admin.py, openipam/hosts/forms.py, openipam/hosts/models.py, openipam/network/admin.py, openipam/network/forms.py, openipam/network/models.py, openipam/report/templates/report/lease_usage.html, openipam/user/templates/admin/user/user/object_history.html, package.json
Model ui updates, bug fixes to api lease usage, etc.
=> more changes for django 2.

openipam/core/views.py, openipam/network/admin.py
Adds the ability to search netmasks and show static vs dynamic addresses. This also fixes a bug where the user cannot access their profile if they have no name.
=> Address search enhancements

openipam/api/views/hosts.py
=> Fix bad merge

.pre-commit-config.yaml
Try to fix python 3.7 vs 3.8 issues once and for all, update pre-commit-hooks
=> Pre commit updates

.pre-commit-config.yaml, openipam/core/views.py
=> Added check that the next redirect is not None

.pre-commit-config.yaml, openipam/hosts/management/oui_import.py
=> Cast shift to an int to make sure the shift works

.pre-commit-config.yaml, openipam/api/autocomplete_light_registry.py
Fixes openipam issue #openipam-be
=> Added check to make sure is_ipamadmin exists

.pre-commit-config.yaml, openipam/hosts/views.py
Fixes openipam issue:
- openipam-c5
- openipam-cx
=> Added check of whether too many values in hosts

.pre-commit-config.yaml, openipam/api/views/report.py
Fixes issue #OPENIPAM-AS
If ports.ifoutoctest_rate or in rate is null then just set the rate to 0
=> Added checks to see if ports has null values

.pre-commit-config.yaml, openipam/conf/settings.py, openipam/hosts/managers.py
Fixes issues:
- OPENIPAM-AE
- OPENIPAM-AH
- OPENIPAM-C0
=> Validate incoming hostname before inserting to database

openipam/api/autocomplete_light_registry.py, openipam/api/filters/guests.py, openipam/api/filters/network.py, openipam/api/serializers/network.py, openipam/api/urls.py, openipam/api/views/base.py, openipam/api/views/network.py
=> leases api

openipam/api/views/report.py, openipam/report/templates/report/server_hosts.html
=> Better title, show nac profile in data table

openipam/core/menu.py, openipam/report/templates/report/disabled.html, openipam/report/templates/report/ipam_stats.html, openipam/report/urls.py, openipam/report/views.py
Removed the unused classes, and urls from the reports app.
(was going to add #172 in same PR, but here we are..)
=> Report fixes

openipam/core/menu.py, openipam/report/templates/report/exposed_hosts.html, openipam/report/urls.py, openipam/report/views.py
Changed URL, Title, and Menu item.
=> Updated template to be responsive; Added title, and URL to match report.

openipam/dns/managers.py
Quick fqdn validation for #197
=> Add validation for dns record name

openipam/api/filters/hosts.py, openipam/api/serializers/hosts.py, openipam/api/views/hosts.py
* Changed api views to use pagination
* Changed required permissions to IPAMApiAdminPermission
* Fixed mac host query nonsense
Related: #178
=> Fix GUL recent queries

openipam/api/views/report.py, openipam/report/templates/report/exposed_hosts.html
* Fix XSS issues in the description of a host
* Drastically improve query performance
Include in #203
=> Exposed Hosts Improvements

openipam/api/views/report.py
For the way we are now pulling stats from NOC we need a from and to date range on the model stats.
We can now request JSON data by setting the Accept header to "application/json".
=> Add JSON API route with start and end date ranges

openipam/api/autocomplete_light_registry.py, openipam/hosts/forms.py, openipam/hosts/templates/hosts/host_form.html, openipam/hosts/validators.py
=> Add pre-populated selection for host domain

openipam/api/serializers/dns.py, openipam/dns/validators.py
Fixes to the `/api/dns/add` API endpoint to allow the DNS record creation function of the `openipam-cli` project I am working on to work.
=> DNS API fixes

openipam/autocomplete/urls.py, openipam/autocomplete/views.py, openipam/core/forms.py, openipam/core/urls.py, openipam/dns/forms.py, openipam/dns/static/dns/js/dnsrecord_list.js, openipam/hosts/admin.py, openipam/hosts/forms.py, openipam/hosts/views.py, openipam/log/admin.py, openipam/network/admin.py, openipam/network/forms.py, openipam/user/admin.py, openipam/user/forms.py, pyproject.toml
Autocomplete should now work on every page, assuming DAL has been patched to remove its check for the jQuery version used by django-admin.
Leases can now be searched using CIDR notation.
=> Improved autocomplete, lease searching

openipam/core/backends.py, openipam/core/views.py
Should fix this issue that appears when logging in to [devopenipam](https://devopenipam.usu.edu):
=> Fixed LDAP account group mirroring

openipam/api/serializers/network.py, openipam/api/urls.py, openipam/api/views/network.py, openipam/network/models.py
see https://github.com/openipam/django-openipam/pull/278; moving to its own route
=> move network usage data to its own api route

openipam/api/urls.py, openipam/api/views/report.py
Adds an endpoint, specifically for NOCs dashboard, that queries the lease logs for everything changed/created on any given date range.
=> API: Endpoint for Lease Changes

openipam/api/views/report.py
- For NOC. We are storing leases updated per day in prisma.
- This call will be called after x amount of time on an interval, as the number this endpoint returns changes. 
- Only needed in staging.
=> API: Lease report returns daily data through IPAM db
